export const twoLetterWords = [
    "am", "an", "as", "at", 
    "be", "by", 
    "do", "go", 
    "he", "hi", 
    "if", "in", "is", "it", 
    "me", "my", 
    "no", 
    "of", "on", "or", 
    "so", 
    "to", "up", "us", 
    "we", "it", "at"
];

export const threeLetterWords = [
    "and", "are", 
    "bat", "cat", "mat", "hat", "rat", 
    "can", "fan", "man", "pan", "ran", "tan", 
    "big", "dig", "fig", "gig", "pig", "wig", 
    "bit", "fit", "hit", "lit", "pit", "sit", 
    "bag", "rag", "tag", 
    "bed", "red", "led", 
    "boy", "toy", "joy", 
    "bad", "dad", "had", "mad", "sad", 
    "cab", "lab", "tab", 
    "cup", "pup", 
    "eat", "fat", "sat", "pat", 
    "for", "nor", 
    "get", "let", "net", "pet", "set", 
    "hot", "not", "pot", "rot", 
    "run", "fun", "sun", 
    "top", "mop", "hop", "pop", 
    "you", "cut", "put", 
    "fix", "mix", 
    "jog", "log", 
    "sip", "tip", "zip", 
    "sit", "hit", "bit", "fit", 
    "aid", "aim", "air", 
    "all", "ill", "old", 
    "any", "why"
  ];
  
  export const phonicsWords = {
    "a": "अ",
    "aa": "आ",
    "i": "इ",
    "ee": "ई",
    "u": "उ",
    "uu": "ऊ",
    "e": "ए",
    "ai": "ऐ",
    "o": "ओ",
    "au": "औ",
    "ka": "क",
    "kha": "ख",
    "g": "ग",
    "gh": "घ",
    "ch": "च",
    "chh": "छ",
    "j": "ज",
    "jh": "झ",
    "t": "ट",
    "th": "ठ",
    "d": "ड",
    "dh": "ढ",
    "n": "ण",
    "t": "त",
    "th": "थ",
    "d": "द",
    "dh": "ध",
    "n": "न",
    "p": "प",
    "ph": "फ",
    "b": "ब",
    "bh": "भ",
    "m": "म",
    "y": "य",
    "r": "र",
    "l": "ल",
    "v": "व",
    "sh": "श",
    "sh": "ष",
    "s": "स",
    "h": "ह",
    "ksh": "क्ष",
    "tr": "त्र",
    "gy": "ज्ञ"
  };
  